// <auto-generated />
namespace StudentAssignment.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class AddingCollegeOfStudentandNametablestoSQL : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddingCollegeOfStudentandNametablestoSQL));
        
        string IMigrationMetadata.Id
        {
            get { return "201802221707280_Adding CollegeOfStudent and Name tables to SQL"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
