// <auto-generated />
namespace StudentAssignment.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class addedmaxlimittomajor : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addedmaxlimittomajor));
        
        string IMigrationMetadata.Id
        {
            get { return "201802221709486_added max limit to major"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
